services:
  analytic_db:
    image: postgres
    environment:
      POSTGRES_USER: analytic_user
      POSTGRES_PASSWORD: analytic_pwd
      POSTGRES_DB: analytic_db
    ports:
      - "5433:5432"
    volumes:
      - "./init:/docker-entrypoint-initdb.d"